### PR TITLE
Handle reorganizations during blocks import

### LINKED ISSUE #50: Thread panic at block 14b054be76b515b12efcfdfd6e5d6bfe39988f937f48768c61e5c01600000000
git @ b0ebed0

Reproducibility: always

Steps:
`pzec import /Zcash/blocks`

What happened:
```
...
2019-03-11 01:29:15  INFO sync Imported 230000 blocks
2019-03-11 01:30:40  INFO sync Imported 231000 blocks
2019-03-11 01:32:00  INFO sync Imported 232000 blocks
2019-03-11 01:33:44  INFO sync Imported 233000 blocks
2019-03-11 01:35:39  INFO sync Imported 234000 blocks
2019-03-11 01:37:24  INFO sync Imported 235000 blocks
thread 'main' panicked at 'Corrupted database - no sprout root for block 14b054be76b515b12efcfdfd6e5d6bfe39988f937f48768c61e5c01600000000', src/libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:325
   7: core::ptr::real_drop_in_place
             at src/libcore/panicking.rs:95
   8: <T as core::any::Any>::get_type_id
             at src/libcore/option.rs:1008
Abort trap: 6
```

Expected result:
All blocks are imported.

### PR DESCRIPTION
**Pull request by svyatonik**
closes #50

### CODE REVIEW

File: sync/src/blocks_writer.rs [hunk 1]
```diff
@@ -102,14 +104,14 @@ impl BlocksWriterSinkData {
 	/// Create new blocks writer data
 	pub fn new(storage: StorageRef) -> Self {
 		BlocksWriterSinkData {
-			storage: storage,
-			err: Mutex::new(None),
+			chain: Chain::new(storage, Arc::new(RwLock::new(MemoryPool::new()))),
```
Comment (NikVolf) [inline sync/src/blocks_writer.rs]: `Arc::new(RwLock::new(MemoryPool::new()))` -> Default::default() ?
